title: Mexican Biobank
url: https://morenolab.github.io
baseurl: /mexican-biobank   # empty "" if publishing from a user/org site root
markdown: kramdown
permalink: pretty           # makes /about/ instead of /about.html
