url: https://www.mxbiobank.org
baseurl: ""
markdown: kramdown
permalink: pretty
title: Mexican Biobank Project
logo: /assets/logos/mexican_biobank_project_white-cropped.svg
google_analytics: G-64K2E2Z13D
