title: Mexican Biobank
url: https://morenolab.github.io
<<<<<<< HEAD
baseurl: /MexicanBiobank_webpage
=======
baseurl: /mexican-biobank   # empty "" if publishing from a user/org site root
>>>>>>> origin/jenkyll_implementation
markdown: kramdown
permalink: pretty           # makes /about/ instead of /about.html
